spring.application.name=sportsystem

# --- DataSource (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/Sport
spring.datasource.username=postgres
spring.datasource.password=naz30june
spring.datasource.driver-class-name=org.postgresql.Driver

# We are not using Spring SQL schema/data initialization
spring.sql.init.mode=never

# Spring Session JDBC tables auto-creation (since spring-session-jdbc is on classpath)
# Change to 'never' after the first successful run if you manage schema manually
spring.session.jdbc.initialize-schema=always

# Optional: show SQL from Spring JDBC logs if needed
# logging.level.org.springframework.jdbc.core=DEBUG
